config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'home/index'
  get '/auth/:provider/callback', :to => 'sessions#callback'
  post '/auth/:provider/callback', :to => 'sessions#callback'
  get '/logout' => 'sessions#destroy', :as => :logout
  get '/tweet' => 'tweet_api#tweet'
  post '/save_git' => 'home#git_create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord

  def self.create_user(auth)
    create! do |user|
      user.provider = auth['provider']
      user.uid = auth['uid']
      user.sreen_name = auth['info']['nickname']
      user.name = auth['info']['name']
      user.token = auth.credentials.token
      user.secret = auth.credentials.secret
    end
  end

  def self.save_github_account(account_id,user_id)
    user = User.find_by(uid: user_id)
    user.update(GithubId: account_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/base_controller.rb
class BaseController < ApplicationController
  protect_from_forgery

  def login_required
    if session[:user_id]
      @current_user = User.find_by(uid: session[:user_id])
    else
      redirect_to root_path
    end

  end

  helper_method :current_user

  private
  def current_user
    @current_user ||= User.find_by(uid: session[:user_id]) if session[:user_id]
  end
end

app/controllers/home_controller.rb
class HomeController < BaseController
  def index
  end

  def git_create
    User.save_github_account(params[:github_id], session[:user_id])
    redirect_to root_path
  end

  def git_update
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def callback
    auth = request.env['omniauth.auth']
    user = User.find_by_provider_and_uid(auth['provider'], auth['uid']) || User.create_user(auth)
    session[:user_id] = user.uid
    redirect_to root_path
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/tweet_api_controller.rb
class TweetApiController < ApplicationController

  def tweet
    require_relative '../services/parse_json_service.rb'

    user_list = User.all

    user_list.each{ |user|
      init(user.token, user.secret)
      commit_count = ParseJsonService.new.create_tweet
      update(create_text(commit_count, user.GithubId))
    }
  end

  private
  def init(user_token,user_secret)
    @client = Twitter::REST::Client.new do |config|
      config.consumer_key = "nRlCKe4Aug0qyu7CIdmYBmIxc"
      config.consumer_secret = "B02QAH13KqLC68G2hdVdPmyLbNMlfRCCOM7KFDXWK0ycdWRpO6"
      config.access_token = user_token
      config.access_token_secret = user_secret
    end
  end

  private
  def update(text)
    begin
      @client.update(text)
      redirect_to root_path
    rescue => e
      p e.message
    end
  end

  private
  def create_text(count, github_id)
    '今日はGithubに' + count.to_s + '回commitしました。https://github.com/' + github_id
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/base_helper.rb
module BaseHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tweet_api_helper.rb
module TweetApiHelper
end

app/views/home/index.html.slim
h1
  | Home#index
p
  | Find me in app/views/home/index.html.erb

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | GithubCommitCountRails
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    meta[charset="UTF-8"]
    meta[http-equiv="X-UA-Compatible" content="IE=Edge"]
    meta[name="viewport" content="width=device-width, initial-scale=1"]
    javascript:
      $(function(){
        update_hidden();
        $('#chenge_account').click(function(){
          update_show()
        })

        function cancel(){
          console.log("test")
          update_hidden();
        }

        function update_hidden(){
          $('#update_account').hide();
          $('#github_id').hide();
          $('#update_submit').hide();
          $('#cancel').hide();

          $('#chenge_account').show();
        }

        function update_show(){
          $('#chenge_account').hide();

          $('#update_account').show();
          $('#github_id').show();
          $('#update_submit').show();
          $('#cancel').show();
        }
      });
    body.container
      .row
        .col-sm-6.col-md-4.col-md-offset-4
          h1.text-center.login-title
            | Count Your today's Github Commit
          .account-wall
            p.center
              label#title
                | あなたの今日のコミット回数をツイートします
            - if current_user
              h4 Twitter Account @ #{current_user.name}
              - if current_user.GithubId == nil
                p.margin_top
                | githubのアカウントIDを入力してください。
                = form_tag(save_git_path, method:'post') do
                  = text_field_tag :github_id, '', class: 'form-control',placeholder: 'GithubのアカウントID'
                  br
                  = submit_tag 'Submit',class:"btn btn-primary btn-lg btn-block"
              - else
                h4 Github Account @ #{current_user.GithubId}
                br
                div.center
                  p.margin-top#chenge_botton_area
                    / = button_to 'Githubアカウント変更','',class:'btn btn-primary btn-sm', id:'chenge_account'
                    button#chenge_account.btn.btn-primary.btn-sm
                      | Githubアカウント変更
                    p.margin_top#update_account
                      | githubのアカウントIDを入力してください。
                      = form_tag(save_git_path, method:'post') do
                        = text_field_tag :github_id, '', class: 'form-control',placeholder: 'GithubのアカウントID'
                        br
                        = submit_tag 'Submit',class:"btn btn-primary btn-lg btn-block",id:"update_submit"
                a href="#" id='cancel' onclick="cancel();" キャンセル
              div.margin_top_left
                = link_to 'ログアウト', logout_path
            - else
              p
              | 下記よりTwitterでログインしてください
              div.center
                p.margin_top
                  = link_to 'Sing in to Twitter', '/auth/twitter', class:'btn btn-primary btn-lg active'
                  label.checkbox.pull-left
                  span.clearfix